version: '3.8'
services:
  web:
    build: ./backend/youtube_clone
    command: gunicorn youtube_clone.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    env_file:
      - .env
    expose:
      - "5432"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web